Added help for SQL commands in riak-shell
basho/riak_shell pull request #58
Opened 2016-10-27 14:43 UTC by gordonguthrie

The help is quite summary - but covers all SQL commands and some of the variants
of SELECT queries - simply pointing out functions and ORDER BY, GROUP BY and LIMIT

I have added all the features that will be in 1.5 (ie include DELETE, ORDER BY and
LIMIT).

The help text has been broken out into a module to enable non-technical review
of its contents to be made easier.

2016-10-27 15:15 UTC, javajolt commented on src/riak_shell.erl
> +-define(P, io_lib:format).
Not sure this improves readability.  It's trivial, but non-standard.  Just using the library function would be a bit clearer (surprisingly).

2016-10-27 19:22 UTC, gordonguthrie commented on src/riak_shell.erl
> +-define(P, io_lib:format).
Yeah, but a lot of the lines were breaking the measure - I think I might have abstracted those lines out to `help.erl` though...

Let me check...

2016-10-28 15:05 UTC, javajolt commented
Using a lower-case version of `help` seems to cause the shell to crash:
```
riak-shell(2)>help create;
riak-shell(1)>help CREATE;
*** ERROR: Shell process terminated! (^G to start new job) ***
```

2016-10-28 18:54 UTC, ph07 reviewed
+1

2016-10-28 18:54 UTC, ph07 commented on src/help.erl
> +        "~n"
- Consider adding BLOB data type
- Clarify that VARCHAR are strings, BLOB - binary data (up  to 64k?)

2016-10-28 18:54 UTC, ph07 commented on src/help.erl
> +    "You can use the SHOW table to list all Time Series tables you have created."
Maybe "You can use `SHOW <table-name>` to list ..."?

2016-10-28 18:54 UTC, ph07 commented on src/help.erl
> +        "The QUANTUM function (which is not required) can be used to colocate data "
Please change to "(which is not required, but heavily recommended)"
Otherwise they can easily generate hotspots

2016-10-28 18:54 UTC, ph07 commented on src/help.erl
> +        "The QUANTUM function (which is not required) can be used to colocate data "
Consider adding something like this:
'PRIMARY KEY has two parts - distribution key and local key. It is very important to define them to fit your dataset and expected queries to achieve optimal performance. The distribution key determines where the data will be placed, so usually it would contain combination of unique ID (simple or composite), and QUANTUM based on the timestamps. The local key determines the sorting order on the disk, so local key should be unique for the sample, combining ID(s) and timestamp. Note that IDs should come before timestamp if your primary way to query the data is slice query per specific sensor. '

2016-10-28 18:54 UTC, ph07 commented on src/help.erl
> +        "~n"
SELECT can be used with ORDER BY, GROUP BY, LIMIT clauses. It supports arithmetics on column values and has a variety of aggregation fuctions like COUNT, SUM, MEAN, AVG, MAX, MIN, STDDEV, STDDEV_SAMP, STDDEV_POP

2016-10-28 20:01 UTC, hazen requested changes
Subsequent calls to `help` seems to cause the shell to crash:

```
riak-shell(1)>help SQL;
The following SQL help commands are supported:
CREATE   - using CREATE TABLE statements
DELETE   - deleting data with DELETE FROM
DESCRIBE - examining table structures
EXPLAIN  - understanding SELECT query execution paths
INSERT   - inserting data with INSERT INTO statements
SELECT   - querying data
SHOW     - listing tables

SELECT can be extended with ORDER BY, GROUP BY, LIMIT, support arithmetic and has a variety of functions like COUNT, SUM, MEAN, AVG, MAX, MIN, STDDEV, STDDEV_SAMP, STDDEV_POP

To get more help type 'help SQL SELECT' (replacing SELECT with another statement as appropriate)
riak-shell(2)>help CREATE;
riak-shell(1)>help DELETE;
*** ERROR: Shell process terminated! (^G to start new job) ***
```

2016-10-28 20:01 UTC, hazen commented on src/help.erl
> +help('SQL') ->
Any chance we could make this case-insensitive? Or add a "not found" message when the match failed?  Now it just silently fails.

2016-10-28 20:01 UTC, javajolt commented on src/help.erl
> +        "~n"
Not a bad idea to break up the laundry list of features. The arithmetic clause does seem to be a logical place to break up the list. Also functions is misspelled.

2016-10-28 20:01 UTC, javajolt commented on src/help.erl
> +        "~n"
Probably want to add BLOB help when the feature actually gets added

2016-10-28 20:01 UTC, javajolt commented on src/help.erl
> +        "be set to NOT NULL.~n"
End paren?

2016-10-28 20:01 UTC, javajolt commented on src/help.erl
> +        "An invalid SELECT query will results in EXPLAIN returning an error~n"
result, not results

2016-10-28 20:01 UTC, javajolt commented on src/help.erl
> +        "You can also decorate SELECT statements with ORDER BY, GROUP BY and LIMIT~n"
Did we want to add examples for these? Or separate help entries? OR just link them to the docs page (as you've done)?

2016-10-28 20:01 UTC, javajolt commented on src/help.erl
> +        "An example of the format is shown below:~n"
Is there an example below?

2016-10-28 20:01 UTC, javajolt commented on src/help.erl
> +help(Other) ->
Guessing this is the clause which is not working which is why `help sql;` failed...

2016-10-28 20:01 UTC, javajolt commented on src/help.erl
> +shrink(Atom) ->
`shrink` just removes the `_EXT` suffix, right?  Maybe a more descriptive name would help?

2016-10-31 11:05 UTC, gordonguthrie commented on src/help.erl
> +        "~n"
This is the high level help so the break out of functions and ORDER BY and limit should be done somewhere else (I don't want to make the inshell help too large - we should push to the docs site...

2016-10-31 11:05 UTC, gordonguthrie commented on src/help.erl
> +        "~n"
Yeah, was leaving BLOB until the PR is done - I have added DELETE because that was my PR ;-)

2016-10-31 11:08 UTC, gordonguthrie commented on src/help.erl
> +        "The QUANTUM function (which is not required) can be used to colocate data "
No - we should push to the TS Docs (I have added the warning).

2016-10-31 11:16 UTC, gordonguthrie commented on src/help.erl
> +        "An invalid SELECT query will results in EXPLAIN returning an error~n"
Fixed

2016-10-31 11:17 UTC, gordonguthrie commented on src/help.erl
> +        "You can also decorate SELECT statements with ORDER BY, GROUP BY and LIMIT~n"
There is a balance between long help and going online - I think this is 'a primer' so I am going short... - if users kick off then we can go long...

2016-10-31 11:17 UTC, gordonguthrie commented on src/help.erl
> +        "An example of the format is shown below:~n"
There is now ;-)

2016-10-31 11:17 UTC, gordonguthrie commented on src/help.erl
> +help(Other) ->
Yup

2016-10-31 11:18 UTC, andytill commented
@gordonguthrie @laurenrother is it a good idea to duplicate the docs in a way that the docs team will not maintain?

2016-10-31 11:18 UTC, gordonguthrie commented on src/help.erl
> +shrink(Atom) ->
Fixed

2016-10-31 11:19 UTC, gordonguthrie commented on src/help.erl
> +help('SQL') ->
Made all commands case insensitive

2016-10-31 11:19 UTC, gordonguthrie commented on src/help.erl
> +        "be set to NOT NULL.~n"
Fixed

2016-10-31 11:20 UTC, gordonguthrie commented
Slightly lost with this PR because the comments are multiply appearing on this page...

2016-10-31 11:21 UTC, gordonguthrie commented
Also @javajolt asked for changes and I can't comment on that request directly - so here goes...

The shell crash was caused by an errant `gg:format` my so very bad :-(

2016-11-01 16:11 UTC, javajolt commented
:+1:

2016-11-01 16:12 UTC, hazen approved these changes

2016-11-01 16:19 UTC, merged