Server-side crash reports crash riak-shell
basho/riak_shell pull request #59
Opened 2016-11-01 14:48 UTC by gordonguthrie

Partial fix for https://bashoeng.atlassian.net/browse/RTS-1094

In this world an attempt is made to insert values into a non-existant table.

This itself is a bug - the existence of the table should be checked - instead a crash happens

This crash message is returned to the connection server in `riak_shel`l which then crashes.

This fix makes `riak-shell` well behaved in the presence of unknown crashes server-side
with a push to the user to report the bug to Basho.

The actual bug that triggered it will be fixed in a different PR

2016-11-01 15:02 UTC, andytill commented
@gordonguthrie What is the best way to provoke an error on the server to test this?

2016-11-01 17:21 UTC, gordonguthrie commented
As per the JIRA - don't create a table but try and insert into it:
`INSERT INTO Geo1Checkin VALUES ('family2','series2',1420113600700,'snow',12.2);`

This, or course, will stop causing a crash when I put the fix for that bug in ;-)

2016-11-02 10:48 UTC, andytill requested changes

2016-11-02 10:48 UTC, andytill commented on src/connection_srv.erl
> +    Reply = case riakc_ts:'query'(Connection, SQL, [], undefined, [{datatypes, true}]) of
Does the `query` function name need to be put in single quotes here?

2016-11-02 10:48 UTC, andytill commented on src/connection_srv.erl
> +                    io_lib:format(Msg, ["XXX", Err3])
What is `XXX`?

2016-11-02 10:48 UTC, andytill commented on src/connection_srv.erl
> +                    Msg = "UNEXPECTED ERROR - if you have logging on please send your logfile to Basho (~p): ~s",
Not all errors are going to be logical errors that should be reported so we shouldn't ask for them all as reports, for example timeout or overload.

2016-11-02 10:48 UTC, andytill commented on src/connection_srv.erl
> +                    Err2 = re:replace(Err, "[\r | \n | \t]", " ", [global, {return, list}]),
This could do with being in it's own function and having a unit test, to make it clear what the error format is.

2016-11-02 10:55 UTC, gordonguthrie commented on src/connection_srv.erl
> +                    Msg = "UNEXPECTED ERROR - if you have logging on please send your logfile to Basho (~p): ~s",
These are specifically unexpected errors - but good point...

2016-11-02 10:56 UTC, gordonguthrie commented on src/connection_srv.erl
> +                    io_lib:format(Msg, ["XXX", Err3])
Its bad UX - we give error numbers don't we? Should we have a number for unexpected numbers?

2016-11-02 11:14 UTC, andytill commented on src/connection_srv.erl
> +                    io_lib:format(Msg, ["XXX", Err3])
Where is the error number, is it part of the message?

2016-11-07 09:43 UTC, andytill commented on src/connection_srv.erl
> +    Reply = case riakc_ts:'query'(Connection, SQL, [], undefined, [{datatypes, true}]) of
...because it is a keyword in R15, got it!

2016-11-08 15:25 UTC, javajolt commented on src/connection_srv.erl
> +    Reply = case riakc_ts:'query'(Connection, SQL, [], undefined, [{datatypes, true}]) of
Are we supporting R15? Does the shell even build with R15?

2016-11-15 00:18 UTC, javajolt commented on src/connection_srv.erl
> +                    Msg = "UNEXPECTED ERROR - if you have logging on please send your logfile to Basho: ~s",
This only happens in an unexpected situation? Just wondering we do want the guidance to send the log file to Basho...

2016-11-15 00:34 UTC, javajolt commented
:+1: Looks good to me, but I'll leave to @andytill since he had concerns

2016-11-15 09:37 UTC, andytill commented
+1

2016-11-15 09:37 UTC, andytill approved these changes

2016-11-15 09:37 UTC, merged

2016-11-15 09:38 UTC, andytill commented
@javajolt @gordonguthrie  My thoughts are that if people submit bug reports, that is a good thing even if they are for timeouts, we can easily weed out those. So maybe see how it goes then get more specific with the error messages.